---
##
# Configure the
##

#- name: SERVICE | Stop MySQL before applying configuration
#  service:
#    name: "{{ percona_mysql_service }}"
#    state: stopped
- block:
  - name: LINEINFILE | Set LimitNOFILE to infinity (Fixes changed limits warning in log)
    lineinfile:
      path: "{{ percona_mysql_systemd_service }}"
      regexp: '^LimitNOFILE='
      line: LimitNOFILE=infinity
    notify:
      - daemon reload
      - restart mysql

  - name: LINEINFILE | Set LimitNOFILE to infinity (Fixes changed limits warning in log)
    lineinfile:
      path: "{{ percona_mysql_systemd_service }}"
      regexp: '^LimitMEMLOCK='
      line: LimitMEMLOCK=infinity
    notify:
      - daemon reload
      - restart mysql

  - name: TEMPLATE | Apply mysqld.cnf template
    template:
      src: "mysqld.cnf.j2"
      dest: "{{ percona_mysql_config }}"
      owner: root
      group: root
      mode: 0644
    notify: restart mysql

  when: percona_mysql_enabled

- meta: flush_handlers
